const items = [
  {
    id: 001,
    name: "Pollera larga (negro)",
    img: "https://user-images.githubusercontent.com/114262373/248826569-b42bce12-ed6b-462d-bd12-18665dc1d606.jpeg",
    description: "Yo diría que es una pollera campana negra con bolsillos rojos, decorada con filigrina roja en en el borde. Apuntada hacía gente que busca expresarse a su manera. Tiene toques románticos, góticos, y muy leve inspiración victorianos.",
    price: 10.000,
  },
  {
    id: 002,
    name: "",
    img: "",
    description: "",
    price: ,
  },
  {
    id: 003,
    name: "",
    img: "",
    description: "",
    price: ,
  },
  {
    id: 004,
    name: "",
    img: "",
    description: "",
    price: ,
  },
  {
    id: 005,
    name: "",
    img: "",
    description: "",
    price: ,
  },
  {
    id: 006,
    name: "",
    img: "",
    description: "",
    price: ,
  },
  {
    id: 007,
    name: "",
    img: "",
    description: "",
    price: ,
  },
  {
    id: 008,
    name: "",
    img: "",
    description: "",
    price: ,
  },
  {
    id: 009,
    name: "",
    img: "",
    description: "",
    price: ,
  },
]
