const itemsEs = [
  {
    id: 1,
    nameEs: "Pollera larga (negro)",
    img: "https://user-images.githubusercontent.com/114262373/248826569-b42bce12-ed6b-462d-bd12-18665dc1d606.jpeg",
    descriptionEs: "Yo diría que es una pollera campana negra con bolsillos rojos, decorada con filigrina roja en en el borde. Apuntada hacía gente que busca expresarse a su manera. Tiene toques románticos, góticos, y muy leve inspiración victorianos.",
    price: 10.000,
  },
  {
    id: 2,
    nameEs: "null",
    img: "https://via.placeholder.com/150",
    descriptionEs: "null",
    price: 0,
  },
  {
    id: 3,
    nameEs: "null",
    img: "https://via.placeholder.com/150",
    descriptionEs: "null",
    price: 0,
  },
  {
    id: 4,
    nameEs: "null",
    img: "https://via.placeholder.com/150",
    descriptionEs: "null",
    price: 0,
  },
  {
    id: 5,
    nameEs: "null",
    img: "https://via.placeholder.com/150",
    descriptionEs: "null",
    price: 0,
  },
  {
    id: 6,
    nameEs: "null",
    img: "https://via.placeholder.com/150",
    descriptionEs: "null",
    price: 0,
  },
  {
    id: 7,
    nameEs: "null",
    img: "https://via.placeholder.com/150",
    descriptionEs: "null",
    price: 0,
  },
  {
    id: 8,
    nameEs: "null",
    img: "https://via.placeholder.com/150",
    descriptionEs: "null",
    price: 0,
  },
  {
    id: 9,
    nameEs: "null",
    img: "https://via.placeholder.com/150",
    descriptionEs: "null",
    price: 0,
  },
]
